# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  admin.category:
    class: App\Admin\CategoryAdmin
    tags:
      - {
          name: sonata.admin,
          model_class: App\Entity\Category,
          manager_type: orm,
          label: Categories,
        }
  admin.blog_post:
    class: App\Admin\BlogPostAdmin
    tags:
      - {
          name: sonata.admin,
          model_class: App\Entity\BlogPost,
          manager_type: orm,
          label: "Blog posts",
        }
  admin.tag:
    class: App\Admin\TagAdmin
    tags:
      - {
          name: sonata.admin,
          model_class: App\Entity\Tag,
          manager_type: orm,
          label: "Tags",
        }
  admin.sub_tag:
    class: App\Admin\SubTagAdmin
    tags:
      - {
          name: sonata.admin,
          model_class: App\Entity\SubTag,
          manager_type: orm,
          label: "Sub Tags",
        }
